### ISSUE TITLE
Favorite folders

### ISSUE THREAD

**Issue by giorgiobeggiora** [gliviu/atom-favorites#1]
Can you please add the feature to add folders? On click, the tree view should reveal it. Thanks!

**Comment by gliviu** [comment]
It's on my plan. Hope that tree view allow revealing items programmatically.
Also when the folder is not found within tree view I think of creating a new project from it.

**Comment by gliviu** [comment]
If you want to try this feature before I get a chance to release just
```bash
apm uninstall favorites
apm install https://github.com/gliviu/atom-favorites
```
My main concern is how intuitive is the new implementation.

**Comment by giorgiobeggiora** [comment]
I tried it and the new funciontalities work like a charm! Using them i figured out that two other improvements should be great:

USER EXPERIENCE
- access "Favorites" menu using right click on files and folders in tree view and tab bar

PROJECTS
- option: "show only favorites contained in project folders"
- option: "show only favorites contained in project folders' and their ancestor folders"
- option: "show all favorites"

those "options" IMHO are FUNDAMENTAL!!! They are interdependent (i can choose just one) and they works "per project": if i have multiple atom windows opened, say one with 3 project folders attached, and one with other 2 different project folders attached,  each of them consider its own project folders, so if i select the 1st option, in the window with 3 project folders i will see only favorites that are contained in those 3 project folders, grouped per project folder.

Finally, if you also should be able to remember "per project" the selected option, will made this package AWESOME 👍 

Maybe those packages could inspire you (or you may decide to use their functionalities if they are installed). They use a custom projects.cson file to store projects' data.

https://atom.io/packages/project-manager
https://atom.io/packages/project-plus

**Comment by giorgiobeggiora** [comment]
I was forgetting the "rename" function :D absolutely useful when you have two folders with the same name

**Comment by giorgiobeggiora** [comment]
actually, "Favorites" menu is a "File" 's children: is it possible to display it as a "File" 's sibling?

**Comment by gliviu** [comment]
Created tasks from all suggestions.
My plan is to implement the #5 soon as it should be pretty simple.
#2 -  this stuff is useful but could lead to ambiguities and confusion; it needs careful planning.
Menu related features depend on Atom support. Generally anything can be done as it is js/html. It is just a matter of the level of hacks we are willing to put in this project. I'll take a look.
