### ISSUE TITLE
Associate favorites with projects

### ISSUE THREAD

**Issue by gliviu** [gliviu/atom-favorites#2]
@giorgiobeggiora request in #1

> option: "show only favorites contained in project folders"
> option: "show only favorites contained in project folders' and their ancestor folders"
> option: "show all favorites"
> those "options" IMHO are FUNDAMENTAL!!! They are interdependent (i can choose just one) and they works "per project": if i have multiple atom windows opened, say one with 3 project folders attached, and one with other 2 different project folders attached, each of them consider its own project folders, so if i select the 1st option, in the window with 3 project folders i will see only favorites that are contained in those 3 project folders, grouped per project folder.
> 
> Finally, if you also should be able to remember "per project" the selected option, will made this package AWESOME 👍
> 
> Maybe those packages could inspire you (or you may decide to use their functionalities if they are installed). They use a custom projects.cson file to store projects' data.
> 
> https://atom.io/packages/project-manager
> https://atom.io/packages/project-plus

**Comment by giorgiobeggiora** [comment]
Hi! I can't wait for this feature ;)

**Comment by gliviu** [comment]
I think this is already achievable using ie. project-manager.

project.conf
```cson
[
  {
    title: "Proj1"
    paths: [
      'D:\\project-folder1'
      'D:\\project-folder2'
    ]
    settings:
      'editor.showInvisibles': false
      'favorites.paths': [
        'd:\\fav1'
        'd:\\fav2'
      ]
  }
  {
    title: "Proj2"
    paths: [
      'D:\\project-folder3'
      'D:\\project-folder4'
    ]
    settings:
      'editor.showInvisibles': false
      'favorites.paths': [
        'd:\\fav3'
        'd:\\fav4'
      ]
  }
]
```

I have both projects opened in different folders and they show different favorites.

**Comment by giorgiobeggiora** [comment]
It works! Thank you ^_^

**Comment by giorgiobeggiora** [comment]
Atom since 1.26 (just released) supports its own project file

https://github.com/atom/atom/releases/tag/v1.26.0

**Comment by gliviu** [comment]
Nice. Waiting for some UI behind that.

**Comment by giorgiobeggiora** [comment]
please add this feature to the readme, thanks !

**Comment by gliviu** [comment]
You mean the ability to have distinct favorite configs for different projects?
I would do that but there are a couple of project managers for Atom. 
[project-manager](https://atom.io/packages/project-manager) seem to be the most used. For this reason I would just provide the example in the comments above.

**Comment by giorgiobeggiora** [comment]
I think it's worth to mention it. Did you investigate on the "core" project file added in atom 1.26 ?
